-- phpMyAdmin SQL Dump
-- version 5.2.2
-- https://www.phpmyadmin.net/
--
-- Host: mysql
-- Generation Time: Jun 20, 2025 at 07:50 PM
-- Server version: 8.0.41
-- PHP Version: 8.2.27

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `yeti-laravel`
--

--
-- Dumping data for table `bids`
--

UPDATE IGNORE `bids` SET `id` = 1,`lot_id` = 15,`user_id` = 2,`bid_amount` = 501.00,`bid_time` = '2025-06-20 18:53:04',`created_at` = '2025-06-20 19:50:26',`updated_at` = '2025-06-20 19:50:26' WHERE `bids`.`id` = 1;
UPDATE IGNORE `bids` SET `id` = 2,`lot_id` = 15,`user_id` = 2,`bid_amount` = 503.00,`bid_time` = '2025-06-20 18:53:08',`created_at` = '2025-06-20 19:50:26',`updated_at` = '2025-06-20 19:50:26' WHERE `bids`.`id` = 2;
UPDATE IGNORE `bids` SET `id` = 3,`lot_id` = 14,`user_id` = 1,`bid_amount` = 21.00,`bid_time` = '2025-06-20 18:53:41',`created_at` = '2025-06-20 19:50:26',`updated_at` = '2025-06-20 19:50:26' WHERE `bids`.`id` = 3;
UPDATE IGNORE `bids` SET `id` = 4,`lot_id` = 14,`user_id` = 1,`bid_amount` = 22.00,`bid_time` = '2025-06-20 18:53:44',`created_at` = '2025-06-20 19:50:26',`updated_at` = '2025-06-20 19:50:26' WHERE `bids`.`id` = 4;
UPDATE IGNORE `bids` SET `id` = 5,`lot_id` = 4,`user_id` = 2,`bid_amount` = 12300.00,`bid_time` = '2025-06-20 19:49:54',`created_at` = '2025-06-20 19:50:26',`updated_at` = '2025-06-20 19:50:26' WHERE `bids`.`id` = 5;

--
-- Dumping data for table `categories`
--

UPDATE IGNORE `categories` SET `id` = 1,`name` = 'Boards and skis',`slug` = 'boards',`class` = 'boards',`created_at` = '2025-06-20 19:50:26',`updated_at` = '2025-06-20 19:50:26' WHERE `categories`.`id` = 1;
UPDATE IGNORE `categories` SET `id` = 2,`name` = 'Bindings',`slug` = 'attachment',`class` = 'attachment',`created_at` = '2025-06-20 19:50:26',`updated_at` = '2025-06-20 19:50:26' WHERE `categories`.`id` = 2;
UPDATE IGNORE `categories` SET `id` = 3,`name` = 'Shoes',`slug` = 'boots',`class` = 'boots',`created_at` = '2025-06-20 19:50:26',`updated_at` = '2025-06-20 19:50:26' WHERE `categories`.`id` = 3;
UPDATE IGNORE `categories` SET `id` = 4,`name` = 'Clothes',`slug` = 'clothing',`class` = 'clothing',`created_at` = '2025-06-20 19:50:26',`updated_at` = '2025-06-20 19:50:26' WHERE `categories`.`id` = 4;
UPDATE IGNORE `categories` SET `id` = 5,`name` = 'Tools',`slug` = 'tools',`class` = 'tools',`created_at` = '2025-06-20 19:50:26',`updated_at` = '2025-06-20 19:50:26' WHERE `categories`.`id` = 5;
UPDATE IGNORE `categories` SET `id` = 6,`name` = 'Other',`slug` = 'other',`class` = 'other',`created_at` = '2025-06-20 19:50:26',`updated_at` = '2025-06-20 19:50:26' WHERE `categories`.`id` = 6;

--
-- Dumping data for table `items`
--

UPDATE IGNORE `items` SET `id` = 1,`title` = '2014 Rossignol District Snowboard',`slug` = '2014-rossignol-district-snowboard',`description` = 'A lightweight agile snowboard ready to dominate any park with explosive pops and razor-sharp turns.',`price` = 10999,`min_bid` = 12000,`img` = '../img/lot-1.jpg',`timer` = '2025-09-12 23:48:57',`category_id` = 1,`created_at` = '2025-06-20 19:50:26',`updated_at` = '2025-06-20 19:50:26' WHERE `items`.`id` = 1;
UPDATE IGNORE `items` SET `id` = 2,`title` = 'DC Ply Mens 2016/2017 Snowboard',`slug` = 'dc-ply-mens-2016-2017-snowboard',`description` = 'A lightweight agile snowboard ready to dominate any park with explosive pops and razor-sharp turns.\nBi-Ax fiberglass laid in two directions gives this board excellent flex and responsiveness, while symmetrical geometry\ncombined with classic camber profile allows you to confidently hold high speeds. And if you\'re completely exhausted by the end of the riding day,\njust look at your board and smile - the sick graphics by Sean Cliver never leave anyone indifferent.',`price` = 159999,`min_bid` = 12000,`img` = '../img/lot-2.jpg',`timer` = '2025-09-11 23:49:04',`category_id` = 1,`created_at` = '2025-06-20 19:50:26',`updated_at` = '2025-06-20 19:50:26' WHERE `items`.`id` = 2;
UPDATE IGNORE `items` SET `id` = 3,`title` = 'Union Contact Pro 2015 bindings size L/XL\n',`slug` = 'union-contact-pro-2015',`description` = 'A lightweight maneuverable snowboard ready to bring the heat in any park, melting snow with powerful ollies and crisp carves.\nBi-Ax fiberglass laid in two directions gives this board excellent flex and responsiveness, while the symmetrical geometry\ncombined with classic camber profile lets you confidently hold high speeds. And if you\'re completely wiped out by the end of the riding day,\njust look at your board and smile - the awesome graphics by Sean Cliver never fail to impress.',`price` = 8000,`min_bid` = 12000,`img` = '../img/lot-3.jpg',`timer` = '2025-10-02 23:49:09',`category_id` = 2,`created_at` = '2025-06-20 19:50:26',`updated_at` = '2025-06-20 19:50:26' WHERE `items`.`id` = 3;
UPDATE IGNORE `items` SET `id` = 4,`title` = 'DC Mutiny Charcoal snowboard boots',`slug` = 'dc-mutiny-charocal',`description` = 'A lightweight maneuverable snowboard ready to bring the heat in any park, melting snow with powerful ollies and crisp carves.\nBi-Ax fiberglass laid in two directions gives this board excellent flex and responsiveness, while the symmetrical geometry\ncombined with classic camber profile lets you confidently hold high speeds. And if you\'re completely wiped out by the end of the riding day,\njust look at your board and smile - the awesome graphics by Sean Cliver never fail to impress.',`price` = 10999,`min_bid` = 12000,`img` = '../img/lot-4.jpg',`timer` = '2025-06-30 23:49:14',`category_id` = 3,`created_at` = '2025-06-20 19:50:26',`updated_at` = '2025-06-20 19:50:26' WHERE `items`.`id` = 4;
UPDATE IGNORE `items` SET `id` = 5,`title` = 'DC Mutiny Charcoal snowboard jacket',`slug` = 'dc-mutiny-charocal-jacket',`description` = 'A lightweight maneuverable snowboard ready to bring the heat in any park, melting snow with powerful ollies and crisp carves.\nBi-Ax fiberglass laid in two directions gives this board excellent flex and responsiveness, while the symmetrical geometry\ncombined with classic camber profile lets you confidently hold high speeds. And if you\'re completely wiped out by the end of the riding day,\njust look at your board and smile - the awesome graphics by Sean Cliver never fail to impress.',`price` = 7500,`min_bid` = 12000,`img` = '../img/lot-5.jpg',`timer` = '2025-11-13 23:49:18',`category_id` = 4,`created_at` = '2025-06-20 19:50:26',`updated_at` = '2025-06-20 19:50:26' WHERE `items`.`id` = 5;
UPDATE IGNORE `items` SET `id` = 6,`title` = 'Oakley Canopy goggles',`slug` = 'oakley-canopy',`description` = 'A lightweight maneuverable snowboard ready to bring the heat in any park, melting snow with powerful ollies and crisp carves.\nBi-Ax fiberglass laid in two directions gives this board excellent flex and responsiveness, while the symmetrical geometry\ncombined with classic camber profile lets you confidently hold high speeds. And if you\'re completely wiped out by the end of the riding day,\njust look at your board and smile - the awesome graphics by Sean Cliver never fail to impress.',`price` = 5400,`min_bid` = 12000,`img` = '../img/lot-6.jpg',`timer` = '2025-10-01 23:49:22',`category_id` = 6,`created_at` = '2025-06-20 19:50:26',`updated_at` = '2025-06-20 19:50:26' WHERE `items`.`id` = 6;
UPDATE IGNORE `items` SET `id` = 7,`title` = 'Snowboard PRIME Surf',`slug` = 'prime-surf',`description` = 'Features:\nMen\'s snowboard\nFlex: medium\nPurpose: All-mountain, groomed runs\nRider level: beginner, advanced\nTwin-Tip geometry: symmetrical geometry and flex makes the board maximally balanced and versatile and provides maximum mobility for freestyle\nCamber profile: classic board camber provides high stability at speeds and excellent edge hold when carving, as well as explosive pop\nSnowboard construction: CAP\nLight Woodcore: lightweight poplar wood core provides strength and gives uniform flex throughout the board length\nTriaxial Fiberglass: laid in three directions, providing high stiffness, responsiveness and stability\nPolyurethane ABS Sidewalls: high-strength seamless polyurethane sidewalls provide excellent dampening and evenly distribute impact loads\nExtruded 4400 base: durable and easy to maintain\nTank Armour Inserts (16 pcs): durable stainless steel 304 grade inserts\nABS TOPSHEET with UV-Protection: high-quality durable top layer with protection from scratches and UV rays\nSteel edges\n2x4 binding system',`price` = 17780,`min_bid` = 100,`img` = 'img/678d26e85dde6.jpg',`timer` = '2025-10-17 23:49:26',`category_id` = 1,`created_at` = '2025-06-20 19:50:26',`updated_at` = '2025-06-20 19:50:26' WHERE `items`.`id` = 7;
UPDATE IGNORE `items` SET `id` = 8,`title` = 'Termit men\'s insulated jacket',`slug` = 'termit-jacket',`description` = 'Design Features\nCut	\nRegular\nLength	\nMedium\nHood	\nNon-detachable\nClosure	\nZipper\nNumber of pockets	\n2\nSnow skirt	\nNon-detachable\n\nFunctional Features\nWater-repellent treatment	\nYes\nWind protection	\nYes\nInsulation	\nSynthetic\n\nGeneral Characteristics\nSport	\nSnowboarding\nGender	\nMen\nProduct authenticity guarantee	\nYes\n\nComposition\nUpper material	\n100% polyester\nInsulation material	\n100% polyester\nLining material	\n100% polyester\n\nAdditional Characteristics\nInsulation weight per m²	\n100\nManufacturer code	\n124847\nCountry of manufacture	\nChina\nSeason	\nWinter\n\nCare Instructions\nCare recommendations	\nGentle wash 30°C. Do not bleach. Tumble drying prohibited. Ironing prohibited. Dry cleaning prohibited.\nAdditional information	\nWash with special detergent. Do not soak.',`price` = 1999,`min_bid` = 100,`img` = 'img/678d27bc0229e.jpg',`timer` = NULL,`category_id` = 4,`created_at` = '2025-06-20 19:50:26',`updated_at` = '2025-06-20 19:50:26' WHERE `items`.`id` = 8;
UPDATE IGNORE `items` SET `id` = 9,`title` = 'Termit women\'s insulated jacket',`slug` = 'termit-jacket-women',`description` = 'WATERPROOF MEMBRANE\nDry\'vex membrane protects against water penetration and wicks away excess heat and moisture from the body. Waterproof and breathability ratings: 5000 mm / 5000 g/m²/24h.',`price` = 3799,`min_bid` = 150,`img` = 'img/678d28009e8a9.jpg',`timer` = '2025-11-19 23:49:31',`category_id` = 4,`created_at` = '2025-06-20 19:50:26',`updated_at` = '2025-06-20 19:50:26' WHERE `items`.`id` = 9;
UPDATE IGNORE `items` SET `id` = 10,`title` = 'Union Flite Pro snowboard bindings',`slug` = 'union-flite-pro',`description` = 'Union Flite Pro — the lightweight champions among snowboard bindings. This freestyle model is perfect for beginner and progressing snowboarders. Universal discs are compatible with 4x4, 4x2, Channel, 3D mounting systems.\n\nSECURE FIXATION\nForma highback provides good force transmission and stability when controlling the board. TS 4.0 toe strap securely holds the boot. Aluminum buckles feature smooth operation.\n\nDURABILITY\nHeelcup is made from durable Extruded 3D Aluminum that doesn\'t deform under load. It provides optimal heel support and minimizes resistance.\n\nPRECISE ENERGY TRANSFER\nLightweight and stiff baseplate made from super-durable Duraflex material guarantees high performance across a wide range of sub-zero temperatures. Reduced contact area with the board provides even greater responsiveness.\n\nCUSHIONING\nBaseplate is partially made from EVA foam and excellently absorbs impact loads during landings.',`price` = 17599,`min_bid` = 200,`img` = 'img/678d2843dc7d4.jpg',`timer` = '2025-11-12 23:49:35',`category_id` = 2,`created_at` = '2025-06-20 19:50:26',`updated_at` = '2025-06-20 19:50:26' WHERE `items`.`id` = 10;
UPDATE IGNORE `items` SET `id` = 11,`title` = 'Terror Fastec snowboard boots',`slug` = 'terror-fastec',`description` = 'Terror snowboard boots with lace lock on the tongue. Durable waterproof material withstands binding friction and keeps feet warm and dry during riding.\n\nCOMFORT\nHeat-moldable liner with anatomical inserts and ankle support. 3D tongue for additional comfort.\n\nQUICK LACING\nQuick boot lacing system is provided. Putting on won\'t take much time!\n\nCUSHIONING\nEVA foam insole and lightweight rubber sole for cushioning.\n\nWEAR RESISTANCE\nOuter boot is made from durable material. Thanks to this, the model will last more than one season.',`price` = 18719,`min_bid` = 200,`img` = 'img/678d28d18c57d.jpg',`timer` = NULL,`category_id` = 3,`created_at` = '2025-06-20 19:50:26',`updated_at` = '2025-06-20 19:50:26' WHERE `items`.`id` = 11;
UPDATE IGNORE `items` SET `id` = 12,`title` = 'Uvex Pyrit FM Goggles',`slug` = 'uvex-pyrit-fm',`description` = 'Basic mask from Uvex. Frameless construction and mirror lens provide stylish appearance and functionality. Light filter S2 (green base, blue mirror external coating).\n\nUV PROTECTION\nBuilt-in UVA, UVB, and UVC radiation filters provide reliable protection for your eyes.\n\nANTI-FOG PROTECTION\nSupravision coating prevents condensation formation on the lens.\n\nGLASSES COMPATIBILITY\nThe mask can be worn over prescription glasses.\n\nCOMFORT\nVelour padding, ventilated frame and silicone-coated strap guarantee comfortable and secure mask fit.',`price` = 7499,`min_bid` = 100,`img` = 'img/678d293d7b705.jpg',`timer` = NULL,`category_id` = 6,`created_at` = '2025-06-20 19:50:26',`updated_at` = '2025-06-20 19:50:26' WHERE `items`.`id` = 12;
UPDATE IGNORE `items` SET `id` = 13,`title` = 'Uvex Splash ski goggles',`slug` = 'maska-gornolyzhnaya-uvex-splash',`description` = 'Lightweight mask for riding in cloudy weather from Uvex.\n\nUV PROTECTION\nLens with built-in filters providing 100% protection from all types of ultraviolet radiation.\n\nANTI-FOG PROTECTION\nSpecial coating prevents the mask from fogging up.',`price` = 3999,`min_bid` = 1000,`img` = 'img/679605dab4c82.jpg',`timer` = '2025-08-22 22:35:45',`category_id` = 6,`created_at` = '2025-06-20 19:50:26',`updated_at` = '2025-06-20 19:50:26' WHERE `items`.`id` = 13;
UPDATE IGNORE `items` SET `id` = 14,`title` = 'Nitro Team TLS snowboard boots',`slug` = 'snoubordicheskie-botinki-nitro-team-tls',`description` = 'Stiff Nitro boots for advanced and professional riders. Suitable for all-mountain riding and backcountry. Removable tongue stiffener allows you to adjust stiffness to your riding style.',`price` = 100,`min_bid` = 20,`img` = 'img/683f3c75171d1.jpg',`timer` = '2025-08-18 22:35:42',`category_id` = 3,`created_at` = '2025-06-20 19:50:26',`updated_at` = '2025-06-20 19:50:26' WHERE `items`.`id` = 14;
UPDATE IGNORE `items` SET `id` = 15,`title` = 'Airhole Balaclava Full Hinge',`slug` = 'balaklava-airhole-balaclava-full-hinge',`description` = 'Comfortable Airhole balaclava with signature breathing hole designed for winter sports. The model reliably protects the face from snow and headwind.',`price` = 4699,`min_bid` = 500,`img` = 'img/68527c37e6425.jpg',`timer` = '2025-08-07 22:35:39',`category_id` = 4,`created_at` = '2025-06-20 19:50:26',`updated_at` = '2025-06-20 19:50:26' WHERE `items`.`id` = 15;
UPDATE IGNORE `items` SET `id` = 16,`title` = 'Airhole Full Hinge balaclava',`slug` = 'airhole-full-hinge-balaclava\n',`description` = 'Comfortable Airhole balaclava with signature breathing hole designed for winter sports. The model reliably protects the face from snow and headwind.',`price` = 4699,`min_bid` = 500,`img` = 'img/68527c37e6425.jpg',`timer` = NULL,`category_id` = 4,`created_at` = '2025-06-20 19:50:26',`updated_at` = '2025-06-20 19:50:26' WHERE `items`.`id` = 16;
UPDATE IGNORE `items` SET `id` = 17,`title` = 'Uvex Wanted helmet',`slug` = 'helmet-uvex-wanted',`description` = 'All-mountain helmet with deep fit Uvex wanted. Durable Hardshell external construction and shock-absorbing EPS inner layer guarantee maximum protection. Lining with additional insulation in the neck area for comfort during riding. Adjustable ventilation maintains optimal microclimate inside the helmet.',`price` = 12999,`min_bid` = 500,`img` = 'img/683f52208745a.jpg',`timer` = NULL,`category_id` = 6,`created_at` = '2025-06-20 19:50:26',`updated_at` = '2025-06-20 19:50:26' WHERE `items`.`id` = 17;
UPDATE IGNORE `items` SET `id` = 18,`title` = 'Snowboard Termit Savage',`slug` = 'snoubord-termit-savage',`description` = 'Savage snowboard from Termit — the perfect choice for freeride enthusiasts. Reliable all-mountain board suitable for riding on high slopes, excellently handles high-speed descents on groomed runs and floats in light powder.',`price` = 27999,`min_bid` = 1000,`img` = 'img/684ffc9078641.jpg',`timer` = NULL,`category_id` = 1,`created_at` = '2025-06-20 19:50:26',`updated_at` = '2025-06-20 19:50:26' WHERE `items`.`id` = 18;

--
-- Dumping data for table `migrations`
--

UPDATE IGNORE `migrations` SET `id` = 1,`migration` = '2014_10_12_000000_create_users_table',`batch` = 1 WHERE `migrations`.`id` = 1;
UPDATE IGNORE `migrations` SET `id` = 2,`migration` = '2014_10_12_100000_create_password_reset_tokens_table',`batch` = 1 WHERE `migrations`.`id` = 2;
UPDATE IGNORE `migrations` SET `id` = 3,`migration` = '2019_08_19_000000_create_failed_jobs_table',`batch` = 1 WHERE `migrations`.`id` = 3;
UPDATE IGNORE `migrations` SET `id` = 4,`migration` = '2019_12_14_000001_create_personal_access_tokens_table',`batch` = 1 WHERE `migrations`.`id` = 4;
UPDATE IGNORE `migrations` SET `id` = 5,`migration` = '2024_09_04_102242_create_categories_table',`batch` = 1 WHERE `migrations`.`id` = 5;
UPDATE IGNORE `migrations` SET `id` = 6,`migration` = '2024_09_04_102353_create_items_table',`batch` = 1 WHERE `migrations`.`id` = 6;
UPDATE IGNORE `migrations` SET `id` = 7,`migration` = '2024_09_10_143237_add_contact_and_avatar_to_users_table',`batch` = 1 WHERE `migrations`.`id` = 7;
UPDATE IGNORE `migrations` SET `id` = 8,`migration` = '2024_09_23_122209_create_pages_table',`batch` = 1 WHERE `migrations`.`id` = 8;
UPDATE IGNORE `migrations` SET `id` = 9,`migration` = '2025_01_20_105833_create_bids_table',`batch` = 1 WHERE `migrations`.`id` = 9;

--
-- Dumping data for table `pages`
--

UPDATE IGNORE `pages` SET `id` = 1,`slug` = 'main',`name` = 'Homepage',`title` = 'Homepage',`content` = NULL,`type` = 'default_value',`route` = 'default_value',`created_at` = '2025-06-20 19:50:26',`updated_at` = '2025-06-20 19:50:26' WHERE `pages`.`id` = 1;
UPDATE IGNORE `pages` SET `id` = 2,`slug` = 'add',`name` = 'Add Lot',`title` = 'Add Lot',`content` = NULL,`type` = 'default_value',`route` = 'lot.create',`created_at` = '2025-06-20 19:50:26',`updated_at` = '2025-06-20 19:50:26' WHERE `pages`.`id` = 2;
UPDATE IGNORE `pages` SET `id` = 3,`slug` = 'lot',`name` = 'Lot',`title` = 'Lot',`content` = '1',`type` = 'default_value',`route` = 'default_value',`created_at` = '2025-06-20 19:50:26',`updated_at` = '2025-06-20 19:50:26' WHERE `pages`.`id` = 3;
UPDATE IGNORE `pages` SET `id` = 4,`slug` = 'viewed-lots',`name` = 'Viewing History',`title` = 'Viewing History',`content` = NULL,`type` = 'default_value',`route` = 'viewed.lots',`created_at` = '2025-06-20 19:50:26',`updated_at` = '2025-06-20 19:50:26' WHERE `pages`.`id` = 4;
UPDATE IGNORE `pages` SET `id` = 5,`slug` = 'register',`name` = 'Registration',`title` = 'Registration',`content` = NULL,`type` = 'default_value',`route` = 'register',`created_at` = '2025-06-20 19:50:26',`updated_at` = '2025-06-20 19:50:26' WHERE `pages`.`id` = 5;
UPDATE IGNORE `pages` SET `id` = 6,`slug` = 'login',`name` = 'Login',`title` = 'Login',`content` = NULL,`type` = 'default_value',`route` = 'login',`created_at` = '2025-06-20 19:50:26',`updated_at` = '2025-06-20 19:50:26' WHERE `pages`.`id` = 6;
UPDATE IGNORE `pages` SET `id` = 7,`slug` = 'search',`name` = 'Search results',`title` = 'Search results',`content` = NULL,`type` = 'default_value',`route` = 'search',`created_at` = '2025-06-20 19:50:26',`updated_at` = '2025-06-20 19:50:26' WHERE `pages`.`id` = 7;
UPDATE IGNORE `pages` SET `id` = 8,`slug` = 'search-suggestions',`name` = 'Search suggestions',`title` = 'Search suggestions',`content` = NULL,`type` = 'default_value',`route` = 'search.suggestions',`created_at` = '2025-06-20 19:50:26',`updated_at` = '2025-06-20 19:50:26' WHERE `pages`.`id` = 8;
UPDATE IGNORE `pages` SET `id` = 9,`slug` = 'category',`name` = 'Category',`title` = 'Category',`content` = '1',`type` = 'default_value',`route` = 'default_value',`created_at` = '2025-06-20 19:50:26',`updated_at` = '2025-06-20 19:50:26' WHERE `pages`.`id` = 9;
UPDATE IGNORE `pages` SET `id` = 10,`slug` = 'profile',`name` = 'Account',`title` = 'Account',`content` = NULL,`type` = 'default_value',`route` = 'profile',`created_at` = '2025-06-20 19:50:26',`updated_at` = '2025-06-20 19:50:26' WHERE `pages`.`id` = 10;

--
-- Dumping data for table `users`
--

UPDATE IGNORE `users` SET `id` = 1,`name` = 'Kate',`email` = 'kvilcins@gmail.com',`email_verified_at` = NULL,`password` = '$2y$12$NV3fmUuenDnKtGBd/x1Q0uSmn/od/4g2w6cFByXaq0s0u4gYPu8IW',`remember_token` = NULL,`created_at` = '2025-06-20 18:55:09',`updated_at` = '2025-06-20 18:56:25',`contact_details` = NULL,`avatar` = 'avatars/VlWQ7EYKTB4JxVWaBPfSvtfGQvXdh5sSEOJUbNVr.webp' WHERE `users`.`id` = 1;
UPDATE IGNORE `users` SET `id` = 2,`name` = 'test',`email` = 'test@gmail.com',`email_verified_at` = NULL,`password` = '$2y$12$bFzEnQewNYtTqLu6Lw4lYOyKiftPIaLS9r9KR.jNgrEWYoi318wNm',`remember_token` = NULL,`created_at` = '2025-06-20 18:55:09',`updated_at` = '2025-06-20 18:55:09',`contact_details` = NULL,`avatar` = NULL WHERE `users`.`id` = 2;
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
