<?php return array (
  0 => 
  array (
    'id' => 1,
    'email' => 'kvilcins@mail.ru',
    'name' => 'Kate',
    'password' => '$2y$12$./ra4/2XPRFQZPU2AOn1VuNen11ZrBuPVaO26PFWfWkFa9IQRMkSm',
    'remember_token' => NULL,
    'email_verified_at' => 
    \Illuminate\Support\Carbon::__set_state(array(
       'endOfTime' => false,
       'startOfTime' => false,
       'constructedObjectId' => '00000000000006a10000000000000000',
       'localMonthsOverflow' => NULL,
       'localYearsOverflow' => NULL,
       'localStrictModeEnabled' => NULL,
       'localHumanDiffOptions' => NULL,
       'localToStringFormat' => NULL,
       'localSerializer' => NULL,
       'localMacros' => NULL,
       'localGenericMacros' => NULL,
       'localFormatFunction' => NULL,
       'localTranslator' => NULL,
       'dumpProperties' => 
      array (
        0 => 'date',
        1 => 'timezone_type',
        2 => 'timezone',
      ),
       'dumpLocale' => NULL,
       'dumpDateProperties' => NULL,
       'date' => '2025-06-22 10:47:13.000000',
       'timezone_type' => 3,
       'timezone' => 'UTC',
    )),
    'created_at' => '2025-06-22T10:32:46.000000Z',
    'updated_at' => '2025-06-24T13:09:46.000000Z',
    'contact_details' => '@katie',
    'avatar' => 'avatars/HYXIEWGVWah2eVLGeH4Gev9eXQsAVkQpaLrgFWbQ.webp',
    'role' => 'admin',
  ),
  1 => 
  array (
    'id' => 2,
    'email' => 'test@gmail.com',
    'name' => 'test',
    'password' => '$2y$12$bFzEnQewNYtTqLu6Lw4lYOyKiftPIaLS9r9KR.jNgrEWYoi318wNm',
    'remember_token' => NULL,
    'email_verified_at' => NULL,
    'created_at' => '2025-06-20T18:55:09.000000Z',
    'updated_at' => '2025-06-20T18:55:09.000000Z',
    'contact_details' => NULL,
    'avatar' => NULL,
    'role' => 'user',
  ),
  2 => 
  array (
    'id' => 3,
    'email' => 'kvilcins@gmail.com',
    'name' => 'Potato',
    'password' => '$2y$12$RSDeAmjiMvODutZFhmXZiuqUCWOTsU0/x.MbgbBr9Bt/Zg/or/zN2',
    'remember_token' => NULL,
    'email_verified_at' => 
    \Illuminate\Support\Carbon::__set_state(array(
       'endOfTime' => false,
       'startOfTime' => false,
       'constructedObjectId' => '00000000000006a80000000000000000',
       'localMonthsOverflow' => NULL,
       'localYearsOverflow' => NULL,
       'localStrictModeEnabled' => NULL,
       'localHumanDiffOptions' => NULL,
       'localToStringFormat' => NULL,
       'localSerializer' => NULL,
       'localMacros' => NULL,
       'localGenericMacros' => NULL,
       'localFormatFunction' => NULL,
       'localTranslator' => NULL,
       'dumpProperties' => 
      array (
        0 => 'date',
        1 => 'timezone_type',
        2 => 'timezone',
      ),
       'dumpLocale' => NULL,
       'dumpDateProperties' => NULL,
       'date' => '2025-06-22 09:26:01.000000',
       'timezone_type' => 3,
       'timezone' => 'UTC',
    )),
    'created_at' => '2025-06-20T18:55:09.000000Z',
    'updated_at' => '2025-06-22T09:26:01.000000Z',
    'contact_details' => NULL,
    'avatar' => NULL,
    'role' => 'user',
  ),
  3 => 
  array (
    'id' => 6,
    'email' => 'kvilcins@list.ru',
    'name' => 'User94',
    'password' => '$2y$12$Sa7A31ejuMFG5rxWHffnsu.8fmT/.k4JHuDduwxWiue0xk/N.h9ZS',
    'remember_token' => NULL,
    'email_verified_at' => 
    \Illuminate\Support\Carbon::__set_state(array(
       'endOfTime' => false,
       'startOfTime' => false,
       'constructedObjectId' => '00000000000006c20000000000000000',
       'localMonthsOverflow' => NULL,
       'localYearsOverflow' => NULL,
       'localStrictModeEnabled' => NULL,
       'localHumanDiffOptions' => NULL,
       'localToStringFormat' => NULL,
       'localSerializer' => NULL,
       'localMacros' => NULL,
       'localGenericMacros' => NULL,
       'localFormatFunction' => NULL,
       'localTranslator' => NULL,
       'dumpProperties' => 
      array (
        0 => 'date',
        1 => 'timezone_type',
        2 => 'timezone',
      ),
       'dumpLocale' => NULL,
       'dumpDateProperties' => NULL,
       'date' => '2025-06-23 12:40:17.000000',
       'timezone_type' => 3,
       'timezone' => 'UTC',
    )),
    'created_at' => '2025-06-22T11:53:26.000000Z',
    'updated_at' => '2025-06-23T12:40:17.000000Z',
    'contact_details' => NULL,
    'avatar' => 'avatars/MqRYI30AGWgVwuTNFejvdTLiCSuJWAtdHP0wfwzU.webp',
    'role' => 'user',
  ),
  4 => 
  array (
    'id' => 7,
    'email' => 'kategarina94@gmail.com',
    'name' => 'Katherine',
    'password' => '$2y$12$kPSBFYvjWmbHImB4ZtfBpOx6hA1mG7MFbBwXvQQgM0a8Oz1x.LbrW',
    'remember_token' => NULL,
    'email_verified_at' => 
    \Illuminate\Support\Carbon::__set_state(array(
       'endOfTime' => false,
       'startOfTime' => false,
       'constructedObjectId' => '00000000000006b10000000000000000',
       'localMonthsOverflow' => NULL,
       'localYearsOverflow' => NULL,
       'localStrictModeEnabled' => NULL,
       'localHumanDiffOptions' => NULL,
       'localToStringFormat' => NULL,
       'localSerializer' => NULL,
       'localMacros' => NULL,
       'localGenericMacros' => NULL,
       'localFormatFunction' => NULL,
       'localTranslator' => NULL,
       'dumpProperties' => 
      array (
        0 => 'date',
        1 => 'timezone_type',
        2 => 'timezone',
      ),
       'dumpLocale' => NULL,
       'dumpDateProperties' => NULL,
       'date' => '2025-06-23 14:17:08.000000',
       'timezone_type' => 3,
       'timezone' => 'UTC',
    )),
    'created_at' => '2025-06-23T14:16:46.000000Z',
    'updated_at' => '2025-06-23T15:35:16.000000Z',
    'contact_details' => '+1 900 000 00 00',
    'avatar' => NULL,
    'role' => 'user',
  ),
);