<?php return array (
  0 => 
  array (
    'id' => 3,
    'email' => 'kvilcins@gmail.com',
    'name' => 'Kate',
    'password' => '$2y$12$RSDeAmjiMvODutZFhmXZiuqUCWOTsU0/x.MbgbBr9Bt/Zg/or/zN2',
    'remember_token' => NULL,
    'email_verified_at' => 
    \Illuminate\Support\Carbon::__set_state(array(
       'endOfTime' => false,
       'startOfTime' => false,
       'constructedObjectId' => '00000000000006a70000000000000000',
       'localMonthsOverflow' => NULL,
       'localYearsOverflow' => NULL,
       'localStrictModeEnabled' => NULL,
       'localHumanDiffOptions' => NULL,
       'localToStringFormat' => NULL,
       'localSerializer' => NULL,
       'localMacros' => NULL,
       'localGenericMacros' => NULL,
       'localFormatFunction' => NULL,
       'localTranslator' => NULL,
       'dumpProperties' => 
      array (
        0 => 'date',
        1 => 'timezone_type',
        2 => 'timezone',
      ),
       'dumpLocale' => NULL,
       'dumpDateProperties' => NULL,
       'date' => '2025-06-22 09:26:01.000000',
       'timezone_type' => 3,
       'timezone' => 'UTC',
    )),
    'created_at' => '2025-06-20T18:55:09.000000Z',
    'updated_at' => '2025-06-22T09:26:01.000000Z',
    'contact_details' => '11111000',
    'avatar' => 'avatars/3f0LSnIX6guUZF0Zz9MUNjRLTiK9X2YNGSGuIGou.webp',
    'role' => 'user',
  ),
  1 => 
  array (
    'id' => 2,
    'email' => 'test@gmail.com',
    'name' => 'test',
    'password' => '$2y$12$bFzEnQewNYtTqLu6Lw4lYOyKiftPIaLS9r9KR.jNgrEWYoi318wNm',
    'remember_token' => NULL,
    'email_verified_at' => NULL,
    'created_at' => '2025-06-20T18:55:09.000000Z',
    'updated_at' => '2025-06-20T18:55:09.000000Z',
    'contact_details' => NULL,
    'avatar' => NULL,
    'role' => 'user',
  ),
  2 => 
  array (
    'id' => 1,
    'email' => 'kvilcins@mail.ru',
    'name' => 'Kate',
    'password' => '$2y$12$8VGRdznxilinX7OaQOxWyuSamjth4rODqRluSeN2DTmmrjenqqtZO',
    'remember_token' => NULL,
    'email_verified_at' => 
    \Illuminate\Support\Carbon::__set_state(array(
       'endOfTime' => false,
       'startOfTime' => false,
       'constructedObjectId' => '00000000000002c20000000000000000',
       'localMonthsOverflow' => NULL,
       'localYearsOverflow' => NULL,
       'localStrictModeEnabled' => NULL,
       'localHumanDiffOptions' => NULL,
       'localToStringFormat' => NULL,
       'localSerializer' => NULL,
       'localMacros' => NULL,
       'localGenericMacros' => NULL,
       'localFormatFunction' => NULL,
       'localTranslator' => NULL,
       'dumpProperties' => 
      array (
        0 => 'date',
        1 => 'timezone_type',
        2 => 'timezone',
      ),
       'dumpLocale' => NULL,
       'dumpDateProperties' => NULL,
       'date' => '2025-06-22 10:47:13.000000',
       'timezone_type' => 3,
       'timezone' => 'UTC',
    )),
    'created_at' => '2025-06-22T10:32:46.000000Z',
    'updated_at' => '2025-06-22T10:47:13.000000Z',
    'contact_details' => '@katie',
    'avatar' => 'avatars/2a0CHZytCqLNxikJM8E0Qtn9VnCatht7IwkvQyYv.webp',
    'role' => 'admin',
  ),
  3 => 
  array (
    'id' => 6,
    'email' => 'kvilcins@list.ru',
    'name' => 'test',
    'password' => '$2y$12$Sa7A31ejuMFG5rxWHffnsu.8fmT/.k4JHuDduwxWiue0xk/N.h9ZS',
    'remember_token' => NULL,
    'email_verified_at' => NULL,
    'created_at' => '2025-06-22T11:53:26.000000Z',
    'updated_at' => '2025-06-22T11:53:26.000000Z',
    'contact_details' => '111111',
    'avatar' => 'avatars/jJ67fkrKyvwTLhq0ZEm40KMb4BnV89e81g4QluLB.webp',
    'role' => 'user',
  ),
);